config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#public'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/recipes', to: 'recipes#index', as: 'recipes'
  get '/public_recipes', to: 'recipes#public', as: 'public_recipes'
  get '/recipes/new', to: 'recipes#new', as: 'recipe_new'
  post 'recipes', to: 'recipes#create', as: 'recipe_create'
  delete 'recipes/:id/delete', to: 'recipes#destroy', as: 'recipe_delete'
  get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  get '/recipes/:recipe_id/new_ingredient', to: 'recipe_foods#new', as: 'ingredient_new'
  post 'recipes/:recipe_id', to: 'recipe_foods#create', as: 'ingredient_create'
  get '/recipes/:recipe_id/update/:id', to: 'recipe_foods#edit', as: 'ingredient_edit'
  put 'recipes/:recipe_id/update/:id', to: 'recipe_foods#update', as: 'ingredient_update'
  delete 'recipes/:recipe_id/delete/:id', to: 'recipe_foods#destroy', as: 'ingredient_delete'
  post '/recipes/:id/toggle', to: 'recipes#toggle', as: 'recipe_toggle'
  get '/recipes/:recipe_id/shopping_list', to: 'recipe_foods#shopping_list', as: 'shopping_list'
  resources :users, only: [:index, :show ]
  resources :foods, only: [:index, :create, :new,  :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= ::User.new
    can :read, :all
    return unless user.present?

    can(:manage, Food, user:)
    can(:manage, Recipe, user:)
    can :manage, RecipeFood, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy, foreign_key: 'food_id'
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy, foreign_key: 'recipe_id'
  validates :name, presence: true
  def total_price
    recipefoods = RecipeFood.includes(:food).where(recipe_id: id)
    total = 0
    recipefoods.each do |item|
      cost = item.food.price * item.quantity
      total += cost
    end
    total
  end

  def total_items
    recipefoods = RecipeFood.where(recipe_id: id)
    recipefoods.length
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :foods, dependent: :destroy, foreign_key: 'user_id'
  has_many :recipes, dependent: :destroy, foreign_key: 'user_id'
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource except: :create
  def index
    @foods = Food.where(user_id: current_user.id)
  end

  def create
    @food = Food.new(food_params)

    @food.user_id = current_user.id

    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      redirect_to foods_path, notice: 'Food was not created.'
    end
  end

  def new
    @food = Food.new
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'Food was successfully destroyed.'
    else
      redirect_to foods_path, notice: 'Food was not destroyed.'
    end
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  load_and_authorize_resource except: :create
  def new
    @recipefood = RecipeFood.new
    @foods = Food.where(user_id: current_user.id)
  end

  def shopping_list
    @recipefoods = RecipeFood.includes(:food).where(recipe_id: params[:recipe_id])
    @recipe = Recipe.find(params[:recipe_id])
    @total = 0
    @items_to_buy = 0
    @recipefoods.each do |recipefood|
      if (recipefood.quantity - recipefood.food.quantity).positive?
        @total += (recipefood.quantity - recipefood.food.quantity) * recipefood.food.price
        @items_to_buy += 1
      end
    end
  end

  def create
    @recipefood = RecipeFood.new(params.require(:recipe_food).permit(:quantity, :food_id, :recipe_id))
    @recipefood.quantity = params[:quantity]
    if @recipefood.save
      redirect_to recipe_path(params[:recipe_id]), notice: 'Food was successfully created.'
    else
      redirect_to recipe_path(params[:recipe_id]), notice: 'Food was not created.'
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @recipefood = RecipeFood.find(params[:id])
  end

  def update
    @recipefood = RecipeFood.find(params[:id])
    if @recipefood.update(params.require(:recipe_food).permit(:quantity))
      redirect_to recipe_path(params[:recipe_id]), notice: 'Food was successfully updated.'
    else
      redirect_to recipe_path(params[:recipe_id]), notice: 'Food was not updated.'
    end
  end

  def destroy
    @recipefood = RecipeFood.find(params[:id])
    @recipefood.destroy
    redirect_to recipe_path(params[:recipe_id]), status: :see_other
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource except: :create
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipefoods = RecipeFood.includes(:food).where(recipe_id: params[:id])
  end

  def public
    @recipes = Recipe.includes(:recipe_foods, :user).where(public: true)
    authorize! :read, @recipes
  end

  def toggle
    @recipe = Recipe.find(params[:id])
    @recipe.toggle! :public
    if @recipe.save
      flash[:success] = 'Post created successfully'
      redirect_to recipe_path
    else
      flash.now[:error] = 'Something went wrong'
      render :new, status: 422
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public))
    @recipe.user = current_user
    if @recipe.save
      flash[:success] = 'Post created successfully'
      redirect_to recipes_path
    else
      flash.now[:error] = 'Something went wrong'
      render :new, status: 422
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource except: :create
  def index
    @users = User.all
    @current_user = current_user
  end

  def show
    @user = User.find(params[:id])
    @recipes = @user.recipes
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <tr> 
    <td>      
      <%= food.name %>
    </td>
  
    <td>     
      <%= food.measurement_unit %>
    </td>
  
    <td>     
      <%= food.price %>
    </td>
  
    <td>      
      <%= food.quantity %>
    </td>  
  
    <td>
    <%= button_to "Destroy", food, method: :delete %>
    </td>
  </tr>
</div>

app/views/foods/_food_table.html.erb
<table  class="table_style">
  <thead>
    <tr class="tr_style">
      <th>Food</th>
      <th>Measurement unit</th>
      <th>Price</th>
      <th>Quantity</th>    
      <th colspan="3">Action</th>
    </tr>
  </thead>
  <tbody>
    <% if @foods.length > 0  %>  
      <% @foods.each do |food| %>    
        <%= render food %> 
      <% end %>
    <% else %>
      <p>There are no foods associated with this user</p>
    <% end %>
  </tbody>
<table>

app/views/foods/_form.html.erb
 <div class="food_form">
  <%= form_with(model: food) do |form| %>
    <% if food.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>
  
        <ul>
        <% food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.label :measurement_unit, style: "display: block" %>
      <%= form.text_field :measurement_unit %>
    </div>
  
    <div>
      <%= form.label :price, style: "display: block" %>
      <%= form.number_field :price, min: 1 %>
    </div>
  
    <div>
      <%= form.label :quantity, style: "display: block" %>
      <%= form.number_field :quantity, min: 1 %>
    </div>
    
    <span>
      <%= form.submit "Add Food", :class => "button_style" %>
    </span>
    
  <% end %>

app/views/foods/index.html.erb
<div class="food_menu_box"
  <div>
  <button type='button' class="button_style">
    <%= link_to "Add food", new_food_path %>
  </button>
  </div> 
</div>
<%= render 'food_table' %>

app/views/foods/new.html.erb
<%= render "form", food: @food %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "foods", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "nav_menu.css", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar">
      <% if user_signed_in? %>        
        <%= render 'shared/nav_menu' %>
        <div>
        <%= button_to 'Log Out', destroy_user_session_path, method: :delete %>
        </div>
      <% end %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/recipe_foods/_ingredient_new.html.erb
<%= form_with model: recipefood, url: ingredient_create_path, method: :post do |f| %>
        <%= f.label 'Ingredient' %>
        <%= f.select :food_id, options_for_select(@foods.collect { |food| [ food.name, food.id ] }) %>
        <%= f.label "Quantity:" %>
        <%= f.number_field :quantity, min: 1 %>
        <%= f.submit "Add Ingredient" %>
      <% end %>

app/views/recipe_foods/_ingredient_update.html.erb
<%= form_with model: recipefood, url: ingredient_update_path(@recipe.id, @recipefood.id), method: :put do |f| %>
        <p><%= recipefood.food.name %></p>
  <%= f.label "Quantity:" %>
  <%= f.number_field :quantity %>
  <%= f.submit "Update Ingredient" %>
<% end %>

app/views/recipe_foods/_shopping.html.erb
<table>
  <tr>
    <th>Food</th>
    <th>Quantity</th>
    <th>Value</th>     
  </tr>
  <% @recipefoods.each do |recipefood|  %>
    <% if recipefood.quantity - recipefood.food.quantity > 0 %>
    <tr>
      <td><%= recipefood.food.name %></td>
      <td><%= recipefood.quantity - recipefood.food.quantity%> <%= recipefood.food.measurement_unit %></td>
      <td>$ <%= (recipefood.quantity - recipefood.food.quantity) * recipefood.food.price %></td>       
    </tr>     
    <% end %>   
  <% end %>   
</table>

app/views/recipe_foods/edit.html.erb
  <body>
    <div class='container'>
      <h2>Update Ingredient:</h2>
      <%= render "ingredient_update", recipefood: @recipefood %>
    </div>
  </body>

app/views/recipe_foods/new.html.erb
  <body>
    <div class='container'>
      <h2>New Ingredient:</h2>
      <%= render "ingredient_new", recipefood: @recipefood %>
    </div>
  </body>

app/views/recipe_foods/shopping_list.html.erb
<h1> Shopping list</h1>
<div class='shopping_counters'>
<h3> Amount of food items to buy: <%= @items_to_buy %> </h3>
<h3> Total value: $ <%= @total %> </h3>
</div>
  <%= render 'shopping' %>

app/views/recipes/_form.html.erb
      <%= form_with model: @recipe, url: recipe_create_path, method: :post do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :description %>
        <%= f.text_area :description %>
        <%= f.label "Preparation Time(hours):" %>
        <%= f.number_field :preparation_time %>
        <%= f.label "Cooking Time(hours):" %>
        <%= f.number_field :cooking_time %>
        <%= f.label :public %>
        <%= f.check_box :public %>
        <%= f.submit "Create Recipe" %>
      <% end %>

app/views/recipes/_ingredients_table.html.erb
<table>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
    <% @recipefoods.each do |recipefood| %>
      <tr>
        <td><%= recipefood.food.name %></td>
        <td><%= recipefood.quantity %> <%= recipefood.food.measurement_unit %></td>
        <td>$ <%= recipefood.quantity * recipefood.food.price %></td>
        <td>
          <% if can? :manage, @recipe%>
            <%= button_to 'Delete', ingredient_delete_path(recipe_id: @recipe.id, id: recipefood.id), method: :delete %>
            <%= link_to 'Modify', ingredient_edit_path(recipe_id: @recipe.id, id: recipefood.id) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>

app/views/recipes/_public_recipes.html.erb
<% @recipes.each do |recipe| %>
    <a href="<%= recipe_path(recipe.id)%>" class='card'>
      <div class='subdiv'>
        <h2><%= recipe.name %></h2>
        <h3>By: <%= recipe.user.name %></h3>
      </div>
      <div class='subdiv'>
        <p>Total food items: <%= recipe.total_items %></p>
        <p>Total price: $<%= recipe.total_price %></p>
      </div>
    </a>
  <% end %>

app/views/recipes/_recipes.html.erb
<% @recipes.each do |recipe| %>
    <div class='card'>
      <div class='subdiv'>
        <a href="<%= recipe_path(recipe.id)%>">
          <h2><%= recipe.name %></h2>
        </a>
        <%= button_to 'Delete', recipe_delete_path(recipe.id), method: :delete %>
      </div>
      <div class='subdiv'>
        <p><%= recipe.description %></p>
      </div>
    </div>
  <% end %>
  <%= link_to 'Add New Recipe', recipe_new_path %>

app/views/recipes/index.html.erb
<section class='container'>
  <%= render 'recipes' %>
</section>

app/views/recipes/new.html.erb
   <body>   
    <div class='container'>
      <h2>New Recipe:</h2>
      <%= render "form", recipe: @recipe %>
    </div>
  </body>

app/views/recipes/public.html.erb
<section class='container'>
  <%= render 'public_recipes' %>
</section>

app/views/recipes/show.html.erb
<section class='container'>
  <h1><%= @recipe.name %></h1>
  <div class='subcontainer'>
    <div class='column-left'>
      <p class='biginfo'>Preparation Time: <%= @recipe.preparation_time %> hs.</p>
      <p class='biginfo'>Cooking Time: <%= @recipe.cooking_time %> hs.</p>
      <p> <%= @recipe.description %> </p>
      <%= link_to 'Generate Shopping List', shopping_list_path(@recipe.id), class: :linkbutton %>
    </div>
    <% if can? :manage, @recipe%>
    <div class='column-right'>
      <div class='togglediv'>
        <p class='togglelabel'>Public</p>
        <%= link_to recipe_toggle_path(@recipe.id), data: { "turbo-method": :post } do %>
          <label class="switch" checked='<%= @recipe.public %>'>
            <input type="checkbox" checked='<%= @recipe.public %>'>
            <span class="slider round" checked='<%= @recipe.public %>'></span>
          </label>
        <% end %>
      </div>
      <%= link_to 'Add Ingredient', ingredient_new_path(@recipe.id), class: :linkbutton %>
      <% end %>
    </div>
  </div>
  <span></span>
  <%= render 'ingredients_table' %>
</section>

app/views/shared/_nav_menu.html.erb
<div>
  <ul class='box'>
    <li class='username'><%= current_user.name %></li>
    <li>|</li>
    <li><%= link_to "Public Recipe", root_path %></li>
    <li>|</li>
    <li><%= link_to "My Recipes", recipes_path %></li>
    <li>|</li>
    <li><%= link_to "Foods", foods_path %></li>
    <li>|</li>   
  </ul>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/index.html.erb
<p ><%= notice %></p>
<h1>Users</h1>
<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

app/views/users/show.html.erb
<p ><%= notice %></p>
<%= render @user %>
<div>
  <%= link_to "Back to users", users_path %>
</div>